name: Fetch Hub Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js with caching
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Fetch and save data
        run: node fetch-json.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Stage all JSON files except hubs-antwerp.json
          git add hub-data/*.json
          git reset hub-data/hubs-antwerp.json
          # Check if there are changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "🤖 Auto-update hub data"
            git push
          else
            echo "No changes to commit."
